const en = {
  locale: 'en-US',
  listSeparator: ', ',
  meeting: 'Meeting',
  back: 'Back',
  createMeeting: 'Create meeting',
  deleteMeeting: 'Delete this meeting',
  role: 'character',
  fellowTraveler: 'Companion',
  you: 'You',
  emptyTitle: 'Plan a meeting that belongs to you',
  emptyBody: 'Choose the characters and opening. Each complete response appears at once, and the ending leaves shared memories for you to review.',
  storyNotStarted: 'The story has not started yet.',
  completedStoryFallback: 'This meeting has ended. Its shared memories are ready to revisit.',
  inProgress: 'In progress',
  ended: 'Ended',
  unnamedMeeting: 'Untitled meeting',
  activeTurns: (count: number) => `In progress · ${count} ${count === 1 ? 'turn' : 'turns'}`,
  sharedMemoriesCount: (count: number) => `Shared memory · ${count} ${count === 1 ? 'person' : 'people'}`,
  activeStories: (count: number) => `${count} ${count === 1 ? 'story is' : 'stories are'} still unfolding`,
  listSubtitle: 'Turn time together into shared memory',
  ongoing: 'Happening now',
  written: 'Written together',
  maxCast: 'A meeting can include up to four characters.',
  selectAtLeastOne: 'Choose at least one character.',
  keepAtLeastOne: 'Keep at least one character in the meeting.',
  needPremise: 'Add a reason for gathering so the characters know why this moment matters.',
  confirmPremise: 'Confirm the premise for this meeting.',
  selectOfflinePreset: 'Choose an offline preset.',
  selectCastRange: 'Choose 1–4 characters.',
  createOfflinePresetFirst: 'Create an offline preset first.',
  createTitle: 'Create meeting',
  inviteSubtitle: 'Invite 1–4 characters into one scene',
  backToList: 'Back to meeting list',
  whoMeeting: 'Who is meeting this time?',
  inviteCharacter: (name: string) => `Invite ${name}`,
  whyHere: 'Why are you meeting here?',
  premisePlaceholder: 'For example: Before the rain stops, you are caught inside a flower shop about to close.',
  titleOptional: 'Meeting title (optional)',
  titlePlaceholder: 'Leave blank to name it from the opening',
  supplementOptional: 'Scene notes (optional)',
  supplementPlaceholder: 'Time, place, relationship context, or something left unsaid.',
  offlinePreset: 'Offline preset',
  personaPrefix: 'This meeting will use your current persona:',
  arrangingScene: 'Preparing the scene…',
  enterMeeting: 'Enter this meeting',
  confirmRsvp: 'Confirm meeting',
  preparingRecentChat: 'Preparing your recent chat…',
  backToChat: 'Back to chat',
  handoffReadyTitle: 'Your chat has already set the scene',
  handoffReadyBody: 'The cast, title, and premise are ready. Review them, then move directly from the online plan into the meeting.',
  whoJoin: 'Who is coming?',
  currentChatCharacter: (name: string) => `${name}, current chat character`,
  meetingTitle: 'Meeting title',
  meetingPremise: 'Why are you meeting?',
  collapsePreset: 'Collapse offline presets',
  changePreset: 'Change offline preset',
  selectedPreset: (name: string) => `Offline preset · ${name}`,
  noneSelected: 'Not selected',
  generatingOpening: 'Writing the opening…',
  startWith: (names: string) => `Start meeting with ${names || 'the characters'}`,
  noReviewSummary: 'This meeting does not yet have a relationship summary to review.',
  sharedMemoryTitle: 'Shared memories',
  sharedMemorySubtitle: 'Review each one. Only selected memories enter the long-term relationship.',
  backToScene: 'Back to meeting',
  includeSummary: (name: string) => `Add the summary with ${name} to memory`,
  memoryWith: (name: string) => `Memory with ${name}`,
  alreadyConfirmed: 'Confirmed',
  willWrite: 'Will enter the relationship timeline',
  willNotWrite: 'Will not enter memory',
  saveSummary: 'Save this summary',
  editSummary: 'Edit this summary',
  editMemory: (name: string) => `Edit the memory summary with ${name}`,
  writingMemory: 'Saving memories…',
  confirmSelected: 'Confirm selected memories',
  finishReview: 'Finish review',
  operationFailed: 'That action could not be completed. Please try again.',
  deleteMeetingTitle: 'Delete this meeting?',
  deleteMeetingBody: (title: string) => `The scene, turns, and unconfirmed summaries in “${title}” will be deleted.`,
  cancel: 'Cancel',
  delete: 'Delete',
  backToMeetingList: 'Back to meeting list',
  closeMeetingMenu: 'Close meeting menu',
  openMeetingMenu: 'Open meeting menu',
  reviewSharedMemory: 'Review shared memories',
  endMeeting: 'End meeting',
  currentStatus: 'Current status',
  peopleCount: (count: number) => `${count} ${count === 1 ? 'person' : 'people'}`,
  collapseStatus: 'Collapse scene status',
  expandStatus: 'Expand scene status',
  currentSceneStatus: 'Current scene status',
  storyLayout: (layout: string) => `Story layout: ${layout}`,
  miniTheater: 'Mini-theater',
  collapseMiniTheater: 'Collapse mini-theater',
  expandMiniTheater: (title: string) => `Expand mini-theater: ${title}`,
  actNumber: (index: number) => `✦  Act ${index}  ✦`,
  collapseActActions: (index: number) => `Collapse actions for act ${index}`,
  openActActions: (index: number) => `Open actions for act ${index}`,
  editTurnInput: 'Edit this turn input',
  localDemoDirector: 'Local demo director',
  failedAct: 'This act did not finish generating. It will not enter the recap or memory until you retry it.',
  saveChanges: 'Save changes',
  generateMiniTheater: 'Generate mini-theater',
  editAct: 'Edit this act',
  retryAct: 'Retry this act',
  deleteAct: 'Delete this act',
  generatingResponse: 'Preparing a complete response. It will appear all at once.',
  composerPlaceholder: 'What do you do, or who do you speak to…',
  composerLabel: 'Meeting scene input',
  sendAct: 'Send this act',
  storyBeforeStart: 'The story is waiting at the opening',
  noStory: 'This meeting did not leave any story text.',
  firstAction: 'Write your first action. The complete response will appear when generation finishes.',
  reviewAndConfirm: 'Review and confirm shared memories',
  startedHandoffTitle: (name: string) => `Meeting with ${name} started`,
  waitingHandoffTitle: (name: string) => `${name} is waiting to meet you`,
  closeHandoffCard: 'Close meeting card',
  openThisMeeting: 'Open this meeting',
  returnToMeeting: 'Return to meeting',
  goToMeeting: 'Go to meeting',
  sceneReadFailed: 'Could not load meeting scenes.',
  modelSummaryMissing: 'The model did not return a reviewable summary.',
  modelSummaryInvalid: 'The model summary format is invalid.',
  missingCastSummary: (characterId: string) => `The scene summary for ${characterId} is missing.`,
  sceneMissing: 'This meeting no longer exists.',
  editTurnMissing: 'Could not find the turn to edit.',
  openingCannotEdit: 'The automatic opening cannot be edited.',
  latestRetryOnly: 'Only the latest turn can be retried.',
  deleteTurnMissing: 'Could not find the turn to delete.',
  openingCannotDelete: 'The automatic opening cannot be deleted.',
  activeSceneOnly: 'Only an active meeting can be ended.',
  selectedSummaryRequired: 'Selected character summaries cannot be empty.',
  miniTheaterTurnMissing: 'Could not find the turn for this mini-theater.',
  manualMiniTheaterDisabled: 'This preset does not allow manual mini-theater generation.',
  currentCharacterMissing: 'The current character is no longer available.',
};

const zh: typeof en = {
  locale: 'zh-CN',
  listSeparator: '、',
  meeting: '见面',
  back: '返回',
  createMeeting: '创建见面',
  deleteMeeting: '删除这场见面',
  role: '角色',
  fellowTraveler: '同行者',
  you: '你',
  emptyTitle: '约一场只属于你们的见面',
  emptyBody: '选好人物和开场，故事会在完整回应后一次出现，并在结束时留下可确认的共同记忆。',
  storyNotStarted: '故事还没有开始',
  completedStoryFallback: '这次见面已经结束，等待你回看共同记忆。',
  inProgress: '进行中',
  ended: '已结束',
  unnamedMeeting: '未命名见面',
  activeTurns: count => `进行中 · ${count} 回合`,
  sharedMemoriesCount: count => `共同回忆 · ${count} 人`,
  activeStories: count => `${count} 场故事仍在继续`,
  listSubtitle: '把一段相处写成共同记忆',
  ongoing: '正在发生',
  written: '已经写下',
  maxCast: '一场见面最多邀请 4 位角色。',
  selectAtLeastOne: '至少选择 1 位角色。',
  keepAtLeastOne: '至少保留 1 位角色。',
  needPremise: '写一句开场缘由，角色才知道此刻为何相聚。',
  confirmPremise: '确认一下这次见面的前提。',
  selectOfflinePreset: '请选择一个离线预设。',
  selectCastRange: '请选择 1–4 名角色。',
  createOfflinePresetFirst: '请先创建一个离线预设。',
  createTitle: '创建见面',
  inviteSubtitle: '邀请 1–4 位角色进入同一场景',
  backToList: '返回见面列表',
  whoMeeting: '这次和谁见面',
  inviteCharacter: name => `邀请${name}`,
  whyHere: '为什么会来到这里',
  premisePlaceholder: '例如：雨停前，你们被困在一间快打烊的花店。',
  titleOptional: '见面标题（可选）',
  titlePlaceholder: '留空时会根据开场自动命名',
  supplementOptional: '场景补充（可选）',
  supplementPlaceholder: '时间、地点、关系背景，或此刻不愿说破的事。',
  offlinePreset: '离线预设',
  personaPrefix: '这场见面会沿用你的当前人设：',
  arrangingScene: '正在布置场景…',
  enterMeeting: '进入这场见面',
  confirmRsvp: '确认赴约',
  preparingRecentChat: '正在整理最近聊天…',
  backToChat: '返回聊天',
  handoffReadyTitle: '聊天已经替你带来了开场',
  handoffReadyBody: '人物、标题和前提都已填好。确认无误后，就从线上约定直接进入见面。',
  whoJoin: '和谁赴约',
  currentChatCharacter: name => `${name}，当前聊天角色`,
  meetingTitle: '见面标题',
  meetingPremise: '这次为什么见面',
  collapsePreset: '收起离线预设',
  changePreset: '更换离线预设',
  selectedPreset: name => `离线预设 · ${name}`,
  noneSelected: '未选择',
  generatingOpening: '正在生成开场…',
  startWith: names => `和${names || '角色'}开始见面`,
  noReviewSummary: '这场见面还没有生成可确认的关系总结。',
  sharedMemoryTitle: '共同记忆',
  sharedMemorySubtitle: '逐一确认，只有勾选的内容会写入长期关系',
  backToScene: '返回场景',
  includeSummary: name => `将与${name}的总结写入记忆`,
  memoryWith: name => `与${name}的记忆`,
  alreadyConfirmed: '已经确认',
  willWrite: '将写入关系时间线',
  willNotWrite: '不会写入记忆',
  saveSummary: '保存这段总结',
  editSummary: '编辑这段总结',
  editMemory: name => `编辑与${name}的记忆总结`,
  writingMemory: '正在写入记忆…',
  confirmSelected: '确认所选记忆',
  finishReview: '完成回看',
  operationFailed: '这次操作没有完成，请稍后再试。',
  deleteMeetingTitle: '删除这场见面？',
  deleteMeetingBody: title => `“${title}”的场景、回合与未确认总结都会被删除。`,
  cancel: '取消',
  delete: '删除',
  backToMeetingList: '返回见面列表',
  closeMeetingMenu: '关闭见面菜单',
  openMeetingMenu: '打开见面菜单',
  reviewSharedMemory: '回看共同记忆',
  endMeeting: '结束见面',
  currentStatus: '此刻状态',
  peopleCount: count => `${count} 人`,
  collapseStatus: '收起场景状态',
  expandStatus: '展开场景状态',
  currentSceneStatus: '当前场景状态',
  storyLayout: layout => `主线排版：${layout}`,
  miniTheater: '小剧场',
  collapseMiniTheater: '收起小剧场',
  expandMiniTheater: title => `展开小剧场：${title}`,
  actNumber: index => `✦　第 ${index} 幕　✦`,
  collapseActActions: index => `收起第 ${index} 幕操作`,
  openActActions: index => `打开第 ${index} 幕操作`,
  editTurnInput: '编辑这一回合的输入',
  localDemoDirector: '本地演示导演',
  failedAct: '这一幕没有完整生成。重试前，它不会进入摘要或记忆。',
  saveChanges: '保存修改',
  generateMiniTheater: '生成小剧场',
  editAct: '编辑这一幕',
  retryAct: '重试这一幕',
  deleteAct: '删除这一幕',
  generatingResponse: '正在组织完整回应，完成后会一次出现。',
  composerPlaceholder: '你想做什么，或对谁说……',
  composerLabel: '见面场景输入',
  sendAct: '发送这一幕',
  storyBeforeStart: '故事停在开场前一刻',
  noStory: '这场见面没有留下正文。',
  firstAction: '写下你的第一个动作，完整回应会在生成完成后一次出现。',
  reviewAndConfirm: '回看并确认共同记忆',
  startedHandoffTitle: name => `已和${name}赴约`,
  waitingHandoffTitle: name => `${name}在等你赴约`,
  closeHandoffCard: '关闭赴约卡',
  openThisMeeting: '打开这场见面',
  returnToMeeting: '回到这场见面',
  goToMeeting: '去见面',
  sceneReadFailed: '见面场景读取失败。',
  modelSummaryMissing: '模型没有返回可审核的总结。',
  modelSummaryInvalid: '模型总结格式无效。',
  missingCastSummary: characterId => `缺少 ${characterId} 的场景总结。`,
  sceneMissing: '这场见面已经不存在。',
  editTurnMissing: '找不到要编辑的回合。',
  openingCannotEdit: '自动开场不能编辑。',
  latestRetryOnly: '只能重试最新一回合。',
  deleteTurnMissing: '找不到要删除的回合。',
  openingCannotDelete: '自动开场不能删除。',
  activeSceneOnly: '只有进行中的场景可以结束。',
  selectedSummaryRequired: '勾选的角色总结不能为空。',
  miniTheaterTurnMissing: '找不到这个小剧场所属的回合。',
  manualMiniTheaterDisabled: '当前预设没有开启手动小剧场。',
  currentCharacterMissing: '当前角色已经不可用。',
};

export type MeetingCopy = typeof en;

export const getMeetingCopy = (language?: string): MeetingCopy => language === 'zh' ? zh : en;
